'use strict';

/**
 * iBag Intelligence Core
 *
 * These constants are the vocabulary of the intelligence system.
 * They deliberately distinguish facts from conclusions and projections.
 */

const INTELLIGENCE_STATUS = Object.freeze({
  OBSERVED: 'OBSERVED',
  DERIVED: 'DERIVED',
  INFERRED: 'INFERRED',
  PROJECTED: 'PROJECTED',
  UNKNOWN: 'UNKNOWN'
});

const INTELLIGENCE_DOMAIN = Object.freeze({
  TRANSACTION: 'TRANSACTION',
  SPENDING: 'SPENDING',
  INCOME: 'INCOME',
  TRANSFER: 'TRANSFER',
  OBLIGATION: 'OBLIGATION',
  RECURRING: 'RECURRING',
  REFUND: 'REFUND',
  REVERSAL: 'REVERSAL',
  ROUNDUP: 'ROUNDUP',
  CASHFLOW: 'CASHFLOW',
  BEHAVIOR: 'BEHAVIOR',
  ANOMALY: 'ANOMALY',
  CHANGE: 'CHANGE',
  OPPORTUNITY: 'OPPORTUNITY',
  FINANCIAL_STATE: 'FINANCIAL_STATE'
});

const CONFIDENCE_LEVEL = Object.freeze({
  VERY_HIGH: 'VERY_HIGH',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INSUFFICIENT: 'INSUFFICIENT'
});

const EVIDENCE_TYPE = Object.freeze({
  SOURCE_TRANSACTION: 'SOURCE_TRANSACTION',
  SOURCE_ACCOUNT: 'SOURCE_ACCOUNT',
  SOURCE_BALANCE: 'SOURCE_BALANCE',
  DERIVED_CALCULATION: 'DERIVED_CALCULATION',
  RELATED_OBSERVATION: 'RELATED_OBSERVATION'
});

const TEMPORAL_STATE = Object.freeze({
  CURRENT: 'CURRENT',
  HISTORICAL: 'HISTORICAL',
  EMERGING: 'EMERGING',
  ESTABLISHED: 'ESTABLISHED',
  CHANGING: 'CHANGING',
  RESOLVED: 'RESOLVED',
  UNKNOWN: 'UNKNOWN'
});

module.exports = {
  INTELLIGENCE_STATUS,
  INTELLIGENCE_DOMAIN,
  CONFIDENCE_LEVEL,
  EVIDENCE_TYPE,
  TEMPORAL_STATE
};
